### ISSUE TITLE
Hit Counter Beta

### ISSUE THREAD

**Issue by styly** [osclass/osclass-plugins#103]
Hi there,

If i want this counter on the main page where i should put the line: <?php hit_counter(); ?>

As well can you make a counter for the number a registered user that will appear on the page to register ?

Cheers.

**Comment by juanramon** [comment]
We haven't done this plugin... Perhaps you should contact the one that made this plugin through the forum (I guess that it would be there where you downloaded the plugin). Sorry :disappointed:
