### ISSUE TITLE
JQuery Social Share

### ISSUE THREAD

**Issue by styly** [osclass/osclass-plugins#104]
In order to use JQuery Social Share Plugin, you should edit your theme files and add the following line of code you want to show social bookmark buttons:

How to do that i don't even know where is the theme files ?

Sorry i'm a noob here

**Comment by juanramon** [comment]
We haven't done this plugin... Perhaps you should contact the one that made this plugin through the forum (I guess that it would be there where you downloaded the plugin). Sorry :disappointed:
