### ISSUE TITLE
Search, car plugin

### ISSUE THREAD

**Issue by R0b3rt0** [osclass/osclass-plugins#106]
Hello, if I activate the car atributtes plugin, the search by make, model, etc.. don't find any result. If I deactivate, the normal search works.

Thanks.

**Comment by conejoninja** [comment]
Hi R0b3rt0,

could you explain a little more your issue?

Thanks

**Comment by alexgreece** [comment]
i had this issue, do you have motorcycle plugin installed? or any other plugin like car attributes? if yes deactivate and it works, motorcycle plugin was made from car plugin and its conflicting

**Comment by mmcsus** [comment]
@alexgreece 

The only way I was able to reproduce your problem was to include motorcycles and cars plugins in the same category. The same for Yachts plugin.

It doesn't make any sense to include them in the same category.

**Comment by alexgreece** [comment]
i did not use them in the same category.... i have a category motorcycles and a category cars and it was not working
