### ISSUE TITLE
Error installing attributes plugin

### ISSUE THREAD

**Issue by sharkey-** [osclass/osclass-plugins#110]
Plugin couldn't be installed because of: Error importSQL::ModelProducts
products_attributes/struct.sql

 I looked for an existing table as I saw on some other threads but they're aren't any to delete.

**Comment by conejoninja** [comment]
Hi sharkey, 

Do you have some more information?
Thanks

**Comment by sharkey-** [comment]
That is where I posted is it not?

You closed it though.  I'm using 3.0.2

I get an error on every single attribute plugin.  This one specifically just says:

Plugin couldn't be installed because of: Error importSQL::ModelProducts
products_attributes/struct.sql

If I run in phpmyadmin I get:

#1005 - Can't create table 'ads1.t_item_products_attr' (errno: 150) 
(<a 
href="server_engines.php?engine=InnoDB&amp;page=Status&amp;token=c809fb4f482dc70425fd90f84b56e0f2">Details...</a>)

This is plugins_products-attributes_3.0.1.  Online searches said that this would be caused by existing key if I remember but I don't have an existing foreign or primary key with these names.

CREATE TABLE /_TABLE_PREFIX_/t_item_products_attr (
    fk_i_item_id INT UNSIGNED NOT NULL,
    s_make VARCHAR(40),
    s_model VARCHAR(60),

```
    PRIMARY KEY (fk_i_item_id),
    FOREIGN KEY (fk_i_item_id) REFERENCES /*TABLE_PREFIX*/t_item (pk_i_id)
```

) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';

Date: Thu, 15 Nov 2012 01:59:59 -0800
