### ISSUE TITLE
Product Attributes Install Error products_attributes

### ISSUE THREAD

**Issue by sharkey-** [osclass/osclass-plugins#111]
I'm using OSClass3.0.2
products-attributes_3.0.1
USA THEME

Plugin couldn't be installed because of: Error importSQL::ModelProducts products_attributes/struct.sql

If I run in phpmyadmin I get:

```
 #1005 - Can't create table 'ads1.t_item_products_attr' (errno: 150) (<a href="server_engines.php?engine=InnoDB&amp;page=Status&amp;token=c809fb4f482dc70425fd90f84b56e0f2">Details...</a>)
```

**Comment by conejoninja** [comment]
Hi sharkey,

Could you paste again the whole error? (the one in phpmyadmin)

I can not see it

Thanks

**Comment by sharkey-** [comment]
```
#1005 - Can't create table 'ads1.t_item_products_attr' (errno: 150) (<a href="server_engines.php?engine=InnoDB& amp;page=Status&amp;token=c809fb4f482dc70425fd90f84b56e0f2">Details...</a>)
```

**Comment by conejoninja** [comment]
Hi,

I could not reproduce the issue. So,

Did you modify the tables somehow ?
Do you have any other plugin installed?
Could you send me a copy of your database?

Thanks

**Comment by sharkey-** [comment]
How would you like the DB sent to you?

Here are the plugins I have;

Ads 4 OSClass
    Manage your advertising strategy.           Enable  Uninstall
Age warning
    Display a warning message about adult content               Install
Dating attributes
    This plugin extends a category of items to store dating attributes such as gender you're looking for and the type of relation.              Install
Facebook Connect
    Use Facebook to connect and log in your users accounts          Enable  Uninstall
Google Analytics
    This plugin adds the Google Analytics script at the footer of every page.               Install
Google Maps
    This plugin shows a Google Map on the location space of every item.                 Install
Ad Importer
    Import ads easily from other sources.               Install
List seller items
    Display all seller items.       Configure   Disable     Uninstall
Location required
    This Plugin makes the location required when posting or editing ads.            Enable  Uninstall
Ley Organica de Proteccion de Datos
    Complete the requirements of the Spanish law for personal data protection (LOPD)                Install

Payment system
    Payment system          Enable  Uninstall
Products attributes
    This plugin extends a category of items to store products attributes such as make, model and so on.                 Install
Rich edit
    Add a WYSIWYG editor when publishing an ad          Disable     Uninstall
Social bookmarks
    Social bookmarks for item detail page           Disable     Uninstall
Voting
    Voting system               Install
Carousel for Osclass
    Displays items in a carousel.       Configure   Disable     Uninstall
Real state attributes
    This plugin extends a category of items to store real estate attributes such as square feets, number of bathrooms, garage, and so on.               Install
Jobs attributes
    This plugin extends a category of items to store jobs attributes such as salary, requirements, timetable, and so on.                Install
Embed Youtube videos
    This plugin extends the item to embed youtube videos.           Disable     Uninstall

**Comment by conejoninja** [comment]
Export it on .sql format (via phpmyadmin for example) and send it to desteban@osclass.org (I will handle all confidential information with care and delete it as soon as I discovered the issue).

Thanks

**Comment by sharkey-** [comment]
DB has been sent.  I think I purged all confidential information already.
If you need access to my site I will provide details to the email you gave above.

**Comment by conejoninja** [comment]
Hi sharkey, 

It's an error of the "engine" of the tables. ALL your tables are "MyISAM", which does not support foreign keys (I wonder how and why osclass is running for you if all your tables are MyISAM!). Please, change them all to innoDB (which support foreign keys and you will be able to install the plugins), EXCEPT t_item_description, which should be MyISAM (for fulltext search).

In short:
Change all your tables from MyISAM to innoDB
Leaves t_item_description as MyISAM
