### ISSUE TITLE
Allow import of custom fields 

### ISSUE THREAD

**Issue by conejoninja** [osclass/osclass-plugins#113]
the xml should be something like
<custom name="field_name">value</custom>

**Comment by xapap** [comment]
That's great news (o:

**Comment by Cojokikl** [comment]
I have 7 clients waiting for this, as soon as we have this solution they will star using osclass!!!!! 

realy great!

**Comment by xapap** [comment]
Any news, i realy need this, is there anything i can do to help with?

**Comment by conejoninja** [comment]
Yes, there're news. Custom fields could be imported now (not released the code yet!) I'm currently working on improving other things of this plugin, so soon there will be a release. Thanks

**Comment by xapap** [comment]
perfect news!! (o:

**Comment by conejoninja** [comment]
It has been released via our market (also available on SF).
