### ISSUE TITLE
new ads not being saved

### ISSUE THREAD

**Issue by conejoninja** [osclass/osclass-plugins#118]
In 3.0.2 - when i try to add a new ad, it's not being saved in database. Apparently however i use "adsense" it's being recognised as "html" in 's_network' in 'oc_t_ads4osc_ads'. 's_code' isn't saved either ...

Easy to fix, but as a reminder ;-)

The original issue is here : https://github.com/osclass/Osclass/issues/546

**Comment by baldhead** [comment]
ok, it only happens when there are "<>" used in the 'code' ... it must be truncated or stripped somewhere ...

**Comment by baldhead** [comment]
fixed ;)

**Comment by conejoninja** [comment]
Hi baldhead, how is it fixed?

**Comment by baldhead** [comment]
i'd like to push my changed file to to the branche, but i don't figure out how to do that ... :)

**Comment by conejoninja** [comment]
Hi,

You have here some info : 
https://help.github.com/articles/creating-a-pull-request
https://help.github.com/articles/using-pull-requests

**Comment by baldhead** [comment]
hmzzz.. did it work? I see i tried to commit my changement, but apparently it says I tried to commit 13 changes! Any idea what i did wrong?

**Comment by conejoninja** [comment]
Nothing wrong, that's normal if the repository was not updated. Don't worry, I will review your changes and approve the pull-request once I have a little time. Thanks a lot

**Comment by baldhead** [comment]
hmmm, that weird as i just forked the repository... i guess i had the most recent version here? I change one file try to create a pull request ...and now it seems like i changed 97 (!) files and 13 commits ...

**Comment by baldhead** [comment]
ah, it's getting clear now - Git is hard to learn when you're used to use svn... specially the branches are pretty new to me...

**Comment by conejoninja** [comment]
Support of this plugin has stopped
