### ISSUE TITLE
Solr

### ISSUE THREAD

**Issue by juanramon** [osclass/osclass-plugins#12]
This plugin should be like the module for [solr in Drupal](http://drupal.org/project/solr): 

It should include: 
- Definition of fields and types 
- Configurator for the Index creator 
- Configurator for the Searcher 
- Configurator for the Highlighter

**Comment by abeel** [comment]
Hi any news ?

**Comment by juanramon** [comment]
@abeel not for now. It's an idea but it's not high priority righ now :( However, I will recommend only to use this with a high volume of items.
