### ISSUE TITLE
Remove cron support

### ISSUE THREAD

**Issue by juanramon** [osclass/osclass-plugins#13]
Now sitemap plugin uses _cron_hourly_ hook. However, we should remove this because sitemap generation uses a lot of recourses. Well, it depends on the size of the site, but it will do a lot of queries. So, I think that it's better to do weekly or create a system cron job manually.

**Comment by conejoninja** [comment]
It will take the same resources if it's called via hook or system's cron. I think we should notify the user somehow instead, letting them know that if they have a big site, it's better to change it to daily or weekly.

I think that by default, we should change it to daily at least.

**Comment by juanramon** [comment]
I think it's better weekly than daily... Most sites wouldn't have a lot of items news every day, so it wouldn't change too much the structure of the sitemap. Also I think that it's very important explain how to enter a manually cron job for this plugin (execute only the sitemap process)

**Comment by conejoninja** [comment]
done, a new file was created which could be called manually, also information was added to help area to achieve that

**Comment by juanramon** [comment]
Change **cron_daily** to **cron_weekly** because in most cases wouldn't be necessary to be generated daily.

**Comment by conejoninja** [comment]
changed
