### ISSUE TITLE
Report bugs on 3.2

### ISSUE THREAD

**Issue by myosclass** [osclass/osclass-plugins#132]
When I update a posting in admin area ( Edit listing) the entire of post disappears plus  counter shows 2 posting in main page but no actual  post exist. There is also a button in Edit listing that says UNBLOCK which does not solve the problem.

Publisher is asked to validate posting by click on a link in email. Publisher does but site still asking do validation until Admin verifies and activate the posting, then posting appears.

Publisher receiving letter to pay for publishing fee although site did not ask or set for fee. Regardless of these, posting will be published because plus when user clicks on related link in email, a message appears says:There was an error There's no need to pay the publish fee

**Comment by conejoninja** [comment]
Wrong place to post the issue, slightly related to payment plugins but looks more than a core issue

**Comment by akifyalcin** [comment]
> Wrong place to post the issue, slightly related to payment plugins but looks more than a core issue
> but I do not use payment plugins.still this problem appears...

[] **how can I get rid of this situation? after moderation of that item,main page counts twice...**

_thanks in advance_,
may
