### ISSUE TITLE
Pagination, property force_limits value incorrect value initialization

### ISSUE THREAD

**Issue by istian** [osclass/osclass-plugins#134]
Hi,

On version OSClass 3.0.2, the pagination class property is using wrong value for force_limits in the __Constructor causing the raw_pages unset the first and the last array value to be unset regardless of value you set for the params.

$this->force_limits       = isset($params['force_limits']) ? (bool) $params['delimiter'] : false;

I'm not sure where to post this issue, I'm not used to github sorry.

Thanks,

**Comment by conejoninja** [comment]
Hi, thanks

I fixed it here : https://github.com/osclass/Osclass/commit/f847774229b0c5e7ffb32ede644dc967a74bc82f

This should have been posted in https://github.com/osclass/Osclass/issues instead of https://github.com/osclass/osclass-plugins/issues, but thanks anyway
