### ISSUE TITLE
spam killer Eror

### ISSUE THREAD

**Issue by Dis555** [osclass/osclass-plugins#136]
Eror.when anyone try to validate his ad by clicking on the validation link is show the following error
0
Warning: Cannot modify header information - headers already sent by (output started at /var/www/data/www/oc-content/plugins/spamkiller/index.php:78) in /var/www/data/www//oc-includes/osclass/core/BaseModel.php on line 72

**Comment by conejoninja** [comment]
Hi Dis555,

Spamkiller is not one of ours plugins, you should contact the plugin's author instead
