### ISSUE TITLE
[Ads4OSC] Ads.php invalid function argument

### ISSUE THREAD

**Issue by KSym04** [osclass/osclass-plugins#137]
On line 20 of Ads.php there is invalid argument error. 

Can be change to :

$conn->osc_dbExec(sprintf("INSERT INTO  %st_ads4osc_ads (`s_code`) VALUES ('%s')", DB_TABLE_PREFIX, $code));

to fix the error. Thanks ;)

**Comment by conejoninja** [comment]
Support of this plugin has stopped
