### ISSUE TITLE
[issue] Permanent Links Changes  on item page

### ISSUE THREAD

**Issue by joaolori** [osclass/osclass-plugins#138]
Hello Guys,
i have issue related with items urls.

if you go here :
http://www.barco.pt/acheter-e-vendre-c210

you will see the url's, some work's other no.

(work) http://cayenne.barco.pt/faire-des-appels-a-1-heure-gratuite-mobile-et-fixe-A1653277

(not work)
http://orleans.barco.pt/le-futur-est-arrive--connectez-telexfree-gratuit-vers-40-paysfixe-et-mobile-A1653307

and replace for this in url bar
http://www.barco.pt/le-futur-est-arrive-connectez-telexfree-gratuit-vers-40-pays-fixe-et-mobile-A1653307

Can you pls tell why this happen?

**Comment by conejoninja** [comment]
Wrong github issues, also this was already fixed
