### ISSUE TITLE
Smf bridge

### ISSUE THREAD

**Issue by admymotor** [osclass/osclass-plugins#140]
I install this plugin, and when my user logs in i get the following error. I have followed the installation and setp the directory path in configuration.

Warning: require_once(/home/admymoto/public_html/oc-content/plugins/smf_bridge/Settings.php) [Function.Require-Once]: failed to open stream: No such file or directory in /home/admymoto/public_html/oc-content/plugins/smf_bridge/user_menu.php on line 8

Fatal error: require_once() [Function.Require]: Failed opening required '/home/admymoto/public_html/oc-content/plugins/smf_bridge/Settings.php' (include_path='/home/admymoto/public_html/oc-includes/htmlpurifier:.:/usr/local/php52/pear') in /home/admymoto/public_html/oc-content/plugins/smf_bridge/user_menu.php on line 8

**Comment by conejoninja** [comment]
This plugins is not developed by Osclass
