### ISSUE TITLE
3.0.2 Recalculating Salary in jobs plugin options results in Fatal Error Line 40

### ISSUE THREAD

**Issue by classadnet** [osclass/osclass-plugins#143]
This error was duplicated with a fresh install of OSclass 3.0.2 with no modifications to any files.

![job_options_recalc_error1](https://f.cloud.github.com/assets/4040496/331780/e2f7c114-9bfc-11e2-9bff-8fa2983af549.jpg)
![job_options_recalc_error2](https://f.cloud.github.com/assets/4040496/331781/eb29b374-9bfc-11e2-99dc-c8bf5a475aeb.jpg)

**Comment by classadnet** [comment]
Forgot to mention:  error is on Hostgator with register_globals=on

**Comment by conejoninja** [comment]
Moved to its own repository
