### ISSUE TITLE
Remove urls without ads

### ISSUE THREAD

**Issue by juanramon** [osclass/osclass-plugins#15]
We shouldn't add urls without ads in the sitemap url. For example:
- If _Houses_ category doesn't have ads, it shouldn't be in the sitemap
- If _Barcelona_ city doesn't have ads, it shouldn't be in the sitemap

It would be nice prepare the code to be able to not include the urls with **n** number of ads in the results, where **n** is an _integer_

**Comment by conejoninja** [comment]
That could be done easily since with the new structure proposed in other issue we'll need to performs search and it returns the number of ads in each search

**Comment by conejoninja** [comment]
as commented, done with the new structure, maybe we use a bit more of procesor but totally worth it
