### ISSUE TITLE
[bug] error when publish item and payment plugin is enabled

### ISSUE THREAD

**Issue by texhiller** [osclass/osclass-plugins#150]
When you publish an item and payment plugin in enabled and click on publish in a white page there is:

Warning: current() expects parameter 1 to be array, null given in /domains/site.com/public_html/oc-content/plugins/payment/index.php on line 175

Warning: Cannot modify header information - headers already sent by (output started at /domains/site.com/public_html/oc-includes/osclass/utils.php:1604) in /domains/site.com/public_html/oc-includes/osclass/utils.php on line 1606

Osclass 3.1.2.
Payment last version
php 5.3

**Comment by conejoninja** [comment]
Moved to its own repository
