### ISSUE TITLE
No Redirect using posted_item Hook with Paypal Plugin Enable HELP PLS

### ISSUE THREAD

**Issue by ghost** [osclass/osclass-plugins#155]
Hello People
Im try to use the posted_item hook after post a new ad. I use this in my functions.php file for redirect to post-sussesfully page:

 function redirect_to_landing($item) {
        osc_get_static_page('post-sussesfully');
        header('Location: ' . osc_static_page_url()); exit;
    }
    osc_add_hook('posted_item', 'redirect_to_landing');
    // add this code in the functions.php of your theme

If I have enable the Paypal plugin, This redirect don't work. If I disable the plugin, the redirect work perfect

I receive this error on the debug file:

[30-May-2013 19:12:16] PHP Warning:  current() [<a href='function.current'>function.current</a>]: Passed variable is not an array or object in /home/user/public_html/oc-content/plugins/paypal/index.php on line 329

Line 329 on Paypal index.php
            $content = current($aPage['locale']);

[30-May-2013 19:12:16] PHP Notice:  Undefined index:  s_title in  /home/user/public_html/oc-content/plugins/paypal/index.php on line 361

Line 329 on Paypal index.php
        $title = osc_mailBeauty($content['s_title'], $words) ;

I use IExplorer 8 and Google Chrome to try, error persist. Working on 3.1.1 OSclass on RealEstate Theme.

Any Help Thanks

**Comment by conejoninja** [comment]
Hi hernan85.

Development of paypal plugin has been stopped, I recommend you to switch to "payments plugin" which is quite similar but improved and updated
