### ISSUE TITLE
Have problems with Cars attributes with Theme Bender Black

### ISSUE THREAD

**Issue by lokilust** [osclass/osclass-plugins#157]
When i install the Cars attributes on Theme Bender it goes all wacky. It works with no problems on all other ones ?

**Comment by conejoninja** [comment]
What do you mean with "wacky"?
Does it happens with any other bender color theme?

**Comment by lokilust** [comment]
Ya it does it to all bender color themes.

I have attached some screen shots from Firefox and Chromim.

Chromim
![car-details-chromim](https://f.cloud.github.com/assets/4175095/679216/5d84e900-d95d-11e2-9771-80b2ed69bd2d.png)

Firefox
![car-details-firefox](https://f.cloud.github.com/assets/4175095/679217/621c39e6-d95d-11e2-92f7-530660f5ef65.png)

**Comment by mmcsus** [comment]
If you take a look at motorcycles attributes plugin it works with all themes in the market.

For cars attributes I've modified that to work with bender themes.

References:
http://forums.osclass.org/plugins/(plugin)-cars-attributes-for-bender-themes/

http://forums.osclass.org/plugins/(plugin)-motorcycles-attributes/

**Comment by conejoninja** [comment]
Moved to its own repository
