### ISSUE TITLE
Sitemap structure

### ISSUE THREAD

**Issue by juanramon** [osclass/osclass-plugins#16]
Now the structure is:
- Categories
- Countries
- Regions
- Cities

The structure should be similar to the one that has [indeed](http://www.indeed.com/find-jobs.jsp).
- Categories
- Categories &raquo; Subcategories
- Categories &raquo; Subcategories &raquo; _Country_ **_(Optional, only for multi-country sites)_**
- Categories &raquo; Subcategories &raquo; _Country_ &raquo; Region
- Categories &raquo; Subcategories &raquo; _Country_ &raquo; Region &raquo; City
- Regions: Inside the region, show the top cities (30)

**Remember**: Only add to the sitemap pages with results

**Comment by conejoninja** [comment]
Done, new structure

**Comment by juanramon** [comment]
What does this code? It returns the cities with more ads? 

``` php
$cities = Search::newInstance()->listCities($region['pk_i_id']);
$l = min(count($cities), 30);
```

P.S.: It's better don't [keep commented code](https://github.com/osclass/osclass-plugins/commit/43ebb457e9459b63ba567cd3527bfd3d0bf87402#L0L35).

**Comment by conejoninja** [comment]
Yes, given a region it return the cities which have at least one item, ordered from more to less items
with  $l = min ... we choose the top 30 cities (unless there're less than 30 cities)
