### ISSUE TITLE
Cars attributes not saving

### ISSUE THREAD

**Issue by kyleonnet** [osclass/osclass-plugins#164]
Hi there

The cars attributes plugin is not saving, not from the front end or admin section. I am running OSClass 3.1.2, and have the newest plugin from the market. I have looked and am having difficulty finding the issue.

If you need any more info I'm happy to assist.

Thanks

**Comment by mmcsus** [comment]
The cars plugin from the market has not been updated.

Try the cars plugin from github:

https://github.com/osclass/osclass-plugins

**Comment by kyleonnet** [comment]
Thanks for the response. I just tried the latest code from that repo (https://github.com/osclass/osclass-plugins/archive/cars_attributes.zip). Uninstalled plugin. Removed old folder. Installed new plugin. I then tried saving from front end (user) and from admin, and neither saved.

**Comment by kyleonnet** [comment]
Found the issue. Posts need to be created after plugin has been installed, otherwise no item will be added into t_item_car_attr to be updated. Might be worthwhile to add a check to see if post exists and if not do an insert instead of an update (if I have time will do so myself). Thanks for the plugin.
