### ISSUE TITLE
Add log in

### ISSUE THREAD

**Issue by juanramon** [osclass/osclass-plugins#18]
There's no option to log in in mobile theme

**Comment by pman89** [comment]
Just enabled log in functionality for my site (http://board.allvbg.ru in russian but button in top left corner will lead you to authorization form), but much more problems appeared. Need to rewrite all theme files, not just main.php, item.php and search.php.

If you want i could send you an ZIP-file with all my changes and comments, still no time to learn git:(

**Comment by juanramon** [comment]
Sure! You can send me the zip-file with all the changes! :-) As I've told you before, a lot of things are not finished :(

**Comment by pman89** [comment]
Added login and logout functionality, by redirecting to page, not using dialogue.

Removed dashboard functionality, by redirecting immediately to homepage, in my opinion, there are no need to use dashboard in mobile theme.

Also, added premium listing in search pages. 

Later I will add styling to register and remind password pages.

**Comment by juanramon** [comment]
I think that the first version would be great if it contains all the features excluding the user part (dashboard)

**Comment by conejoninja** [comment]
Closing this due to being old. If the issue still persists, please reopen.
