### ISSUE TITLE
Minifier - 400 bad request

### ISSUE THREAD

**Issue by fossxplorer** [osclass/osclass-plugins#180]
I've installed and enabled minifier plugin, but it fails for some URLs like for /index.php?page=custom&file=watchlist/watchlist.php and /payment/publish/5 with 
400 Bad Request

Please see http://code.google.com/p/minify/wiki/Debugging..
I've tried to enable debugging inside minifier/config.php, but can't get any debug in the console.
Any help appreciated.
@conejoninja

**Comment by conejoninja** [comment]
Hi,

I'm not sure which plugin are you talking about, but this repository is no longer supported. Plugins have been moved to their own repositories
