### ISSUE TITLE
Buy/Sell Plugin broken

### ISSUE THREAD

**Issue by luckygoyal** [osclass/osclass-plugins#184]
Hi Osclass,

The buy and sell plugin is broken for 3.5.7. Is it possible to upgrade it? How about adding custom fields to it like rent etc.

Thanks

**Comment by conejoninja** [comment]
Plugins has now each own repository, please, post the issues there : https://github.com/osclass/osclass-plugins/blob/master/README.md.

Also, Buy/sell plugin is discontinnued because the same functionality could be achieved with custom fields

**Comment by luckygoyal** [comment]
Thanks.
