### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by luckygoyal** [osclass/osclass-plugins#186]
How about adding a slider in the main page ?

**Comment by conejoninja** [comment]
Plugins has now each own repository, please, post the issues there : https://github.com/osclass/osclass-plugins/blob/master/README.md.

Also, this place is for bugs, problems and issues, not for suggestions about new plugins.

**Comment by luckygoyal** [comment]
Hello Osclass,

Sorry for posting it here. My mistake.

Thanks,
Mayank
