### ISSUE TITLE
double slash issue after domain.com//item

### ISSUE THREAD

**Issue by umeridrisi** [osclass/osclass-plugins#188]
Hello there,

I am experiencing the double slash issue with my site dastiab.com and when I disable friendly urls its look just fine.

What should i do?

**Comment by conejoninja** [comment]
Please ask in the forums : http://forums.osclass.org/

**Comment by umeridrisi** [comment]
But why?

What's the problem to ask here?

Please help me as fast as you can.

**Comment by conejoninja** [comment]
Because this is not the correct place for it. 

Yours looks like a configuration problem, your site looks fine so not sure how to reproduce the issue, please provide more information when you post in the forums if the problem persists.

Also, don't demand urgent help.

**Comment by umeridrisi** [comment]
ok

**Comment by umeridrisi** [comment]
Please check: https://forums.osclass.org/themes-26/double-slash-issue-after-domain-comitem/
