### ISSUE TITLE
Use nice urls

### ISSUE THREAD

**Issue by juanramon** [osclass/osclass-plugins#19]
Use nice urls in sitemap

We can suggest here the structure:
- /browse/c,**category**/
- /browse/c,**category**,**subcategory**/
- /browse/c,**category**,**subcategory**/co,**country**/
- /browse/c,**category**,**subcategory**/co,**country**/re,**region**/
- /browse/c,**category**,**subcategory**/co,**country**/re,**region**/ci,**city**/
- /browse/re,**region**/ci,**city**/

**Comment by conejoninja** [comment]
Need to change OSClass' core first

**Comment by juanramon** [comment]
What should we do? We may adapt the Rewrite Class to allow more rules?

**Comment by conejoninja** [comment]
Closing this due to being old. If the issue still persists, please reopen.
