### ISSUE TITLE
Statis urls generation

### ISSUE THREAD

**Issue by juanramon** [osclass/osclass-plugins#38]
Once it's created the structure to create sitemap.xml (it's almost finished by @conejoninja) it would be nice be able to create some static pages like:
- http://www.indeed.com/find-jobs.jsp
- http://homes.trovit.com/browse

Maybe the best solution will be to save the urls in the database.

**Comment by conejoninja** [comment]
I don't understand. I already didi all the URL described there (searches by location). If you wish to make "osclass.org/browse" and that ALL location url appears, then it has something to do with OSClass' core and not with this plugin...

**Comment by juanramon** [comment]
I think that it could be done in the plugin. If we tell the user to create a new page, for example: _top-searches_, we should be able to create a static page with the urls like http://www.indeed.com/find-jobs.jsp Maybe it wouldn't be a nice page for all the themes, but we can adapt first for modern theme.

**Comment by conejoninja** [comment]
Closing this due to being old. If the issue still persists, please reopen.
