### ISSUE TITLE
Some typo mistakes

### ISSUE THREAD

**Issue by juanramon** [osclass/osclass-plugins#39]
- You are **watcihng** %d items
- In order to work this **pluggin need**  OSClass v2.2 and up
- without this version _the_  pluggin will crash    &middot;     **the** is missing
- You have %s version &middot; order mistake, correct: **You have version %s**
- Of course you can. Watchlist **display** _only_ a link_. Y_ou can use css to make a button or anything else.
- **Did** watchlist plugin work with all version_s_ of OSClass

**Comment by conejoninja** [comment]
Closing this due to being old. If the issue still persists, please reopen.
