### ISSUE TITLE
Item detail cache

### ISSUE THREAD

**Issue by juanramon** [osclass/osclass-plugins#40]
- It should be a parameter to set the expiration of the cache
- Cache should be removed in the next cases:
  - If the item has expired
  - If the item has new comments (active, not only submitted to review)
  - If the item has been modified

> **Bonus**
> - Cache is created on-demand: first time the request page is loaded
> - It only applies for not logged users

**Comment by conejoninja** [comment]
I think the only thing that the plugin is missing is the parameter to set expiration date, but if we really want to make it fast, we should left the parameter hardcoded as it's now...

**Comment by conejoninja** [comment]
Sorry, the parameter was already included, I said nothing ;)
