### ISSUE TITLE
Static pages

### ISSUE THREAD

**Issue by juanramon** [osclass/osclass-plugins#41]
- It should be a parameter to set the expiration of the cache
- Cache should be removed when the page has been modified

> **Bonus**
> - Cache is created on-demand: first time the request page is loaded
> - It only applies for not logged users

**Comment by conejoninja** [comment]
This is done, except for the parameter, check the comment on issue 40

**Comment by conejoninja** [comment]
Sorry, the parameter was already included, I said nothing ;)
