### ISSUE TITLE
Search results + homepage

### ISSUE THREAD

**Issue by juanramon** [osclass/osclass-plugins#45]
- XML feed are included
- It should be a parameter to set the expiration of the cache
- Cache the pages for all the parameters: categories, subcategories, country, region, etc.

> Bonus
> - Cache is created on-demand: first time the request page is loaded
> - It only applies for not logged users

**Comment by conejoninja** [comment]
This is already done. I think we decided not to cache the homepage (because ANY change/publish/etc will require to delete it). But searches are cached (by category, region, country, city, feed, ... and combinations of all of them)
