### ISSUE TITLE
Alignment of buttons

### ISSUE THREAD

**Issue by trendless** [osclass/osclass-plugins#50]
The buttons that show up below an item are out of alignment on IE8, and the middots between are out of place on Chrome.

http://imgur.com/a/vaYfb

**Comment by trendless** [comment]
using twitter_bootstrap theme

**Comment by juanramon** [comment]
Yep, between the twitter design and the social bookmark plugin.

**Comment by juanramon** [comment]
Added list-style:none to ul tag
