### ISSUE TITLE
Sitemap gen ver 1.1 install error

### ISSUE THREAD

**Issue by eyework247** [osclass/osclass-plugins#58]
Error occurred while installing sitemap gen latest version. Please fix and tell the solution.

---

There was a fatal error and the plugin was not installed.
Error: "Undefined index: s_name" Line 92

**Comment by conejoninja** [comment]
I have Osclass 2.3.1

When I install Sitemap show this error.
There was a fatal error and the plugin was not installed.
Error: "Invalid argument supplied for foreach()" Line: 87
File: /home/delta/public_html/oc-content/plugins/sitemap_generator/index.php

**Comment by TurbineJesse** [comment]
I'm receiving this error as well with OSClass 2.3.1 (BCute latest). The plugin uploads fine, but when I click "Install", I get the following error:

There was a fatal error and the plugin was not installed.
Error: "Invalid argument supplied for foreach()" Line: 87
File: /home/tlink/public_html/osclass/oc-content/plugins/sitemap_generator/index.php

**Comment by conejoninja** [comment]
I fixed both errors, the problem on line 87 was of OSClass' core (it will not work until you upgrade osclass to 2.3.2 or newer).

You could fix it manually modifying oc-includes/osclass/model/Region.php

line 69 from

```
        $this->findByCountry($countryId) ;
```

to 

```
        return $this->findByCountry($countryId) ;
```
