### ISSUE TITLE
PayPal plugin bug - can't select a category during ad editing

### ISSUE THREAD

**Issue by TurbineJesse** [osclass/osclass-plugins#59]
This is a bug with the PayPal plugin. I'm using OSClass 2.2.3 with BCute 1.1.3.

THE PROBLEM: When EDITING an ad with the PayPal plugin enabled, the user is unable to select a category.

SUMMARY:
I was testing out some features and went to edit an ad... I went to SAVE, then an error came up that I needed to select a category. But, I could not. The only category that was listed was the current category. However, since I have the categories setting "Selectable parent categories" unchecked, I could not do this either (because the current category is displayed as a "parent" category, so it can't be selected).

When enabling/disabling plugins one-by-one, I discovered this error only occurs when the PayPal plugin is enabled with the option "Pay per post ads" checked. I've been unable to fix this.

UPDATE: I believe what is happening is, since there is only one category listed in the drop-down box, it is being treated as a "parent" category. And since under the Category settings, "Selectable parent categories" is unchecked (disabled), there is NO way to even select that one and only category.... hence, there is no way to save/edit an ad.

Jesse

**Comment by conejoninja** [comment]
This issue has been fixed in version 2.3
