### ISSUE TITLE
Car Attributes

### ISSUE THREAD

**Issue by trains58554** [osclass/osclass-plugins#6]
In the admin panel managing makes, models, and vehicle types does not allow you to delete even if you create a new field in one the tables and try to delete it right away.

Jay

**Comment by juanramon** [comment]
I cannot reproduce the same error. I'm not able to delete makes/models/vehicle types in case that have attached some items. 

You're not able to remove any make/model/vehicle type or only the ones that are used in the items?

**Comment by trains58554** [comment]
I tried to just add a new vehicle type and was not able to delete it and it was not attached to any item.

**Comment by trains58554** [comment]
Ok I just found found a solution in the button tag you need to add type="button" this is the button tag around the delete button. My guess is that my browser was interpreting it as a submit button.

**Comment by juanramon** [comment]
mm... maybe. Which browser are you using?

**Comment by trains58554** [comment]
I am using firefox 5 I just recently upgraded to this version I think it worked fine in the past versions but I cannot remember if it did.
