### ISSUE TITLE
YouTube bug - short URL's don't work

### ISSUE THREAD

**Issue by TurbineJesse** [osclass/osclass-plugins#60]
Short and simple.... the YouTube plugin does not work when using YouTube's default "short" URL. There is no error generated, but the video simply does not show up on the item page.  Long URL's work just fine.

This does NOT work (default short URL): http://youtu.be/BcYc5nJmUMU

This DOES work (long url): http://www.youtube.com/watch?v=BcYc5nJmUMU

I did take a look in the SQL database table for this plugin.... an entry is recorded when using a long URL, but if you use a "short" URL, the database field for that ad item is blank.

I'm using all the latest... OSClass 2.2.3, BCute 1.1.3, and the current YouTube plugin.

**Comment by conejoninja** [comment]
Plugin has been updated to support short url

**Comment by TurbineJesse** [comment]
Fantastic! Thanks! I just installed this latest update (0.9.4) and it works great.
