### ISSUE TITLE
YouTube - spelling error in plugin name - very minor

### ISSUE THREAD

**Issue by TurbineJesse** [osclass/osclass-plugins#64]
This is very, very minor.....

The title for the YouTube plugin is misspelled when viewing from the "Manage plugins" feature in the dashboard....

This is how it currently reads....
Name: "Embed youtuve videos"

I don't think I need to state what's wrong with that! ;-)

Jesse

**Comment by conejoninja** [comment]
The issue is fixed on git repository, I will not make a package until another modification or a couple of days. ;)
