### ISSUE TITLE
Sitemap generation bug.

### ISSUE THREAD

**Issue by conejoninja** [osclass/osclass-plugins#66]
In sitemap generation "–" is replaced by – This causes sitemap to get corrupt. I found several times that my sitemap was marked as having error by Google webmaster tools. Viewing my sitemap in firefox highlighted the XML Parse error caused by –

This issue is a copy of this one (placed on the wrong github) : https://github.com/osclass/OSClass/issues/82

**Comment by ghost** [comment]
"–" is replaced by "& n d a s h ;" <-------- remove the spaces

**Comment by conejoninja** [comment]
Ok thanks, that makes more sense ;) We'll work on that

**Comment by conejoninja** [comment]
This doesn't apply anymore
