### ISSUE TITLE
PayPal plugin sends payment requests for $0 ads

### ISSUE THREAD

**Issue by conejoninja** [osclass/osclass-plugins#67]
With "Pay per post ads" enabled, categories marked as $0 still generate an emailing requesting payment, however rolling the payment link returns an error stating the payment has already been made.

If one wants a mixture of both free and paid ads, how can the payment request email be deactivated for free ads?

Original bug report here : https://github.com/osclass/OSClass/issues/85

**Comment by rnkn** [comment]
Any progress on this?

**Comment by conejoninja** [comment]
Closing this due to being old. If the issue still persists, please reopen.

Please check the new Payment plugin, it should work as a replacement for paypal plugin
