### ISSUE TITLE
Location Required has no effect

### ISSUE THREAD

**Issue by rnkn** [osclass/osclass-plugins#68]
After installing the location_required plugin when attempting to post an ad through the public interface without any location information the ad still validates and posts. Locations can also be added or deleted from ads via the email edit link. The plugin appears to have no effect.

N.B. I have changed the autocomplete locations to drop-down menu locations as per http://wiki.osclass.org/Changing_between_drop-down_and_autocomplete_for_locations

Same result in Safari and Firefox.
OSClass 2.3.3
DreamHost PHP 5.2 FastCGI

**Comment by trains58554** [comment]
Hi @rnkn,

Which theme are you using? 

Jay

**Comment by rnkn** [comment]
I'm using a customised theme, but I also reproduced this with an unaltered Modern theme by changing the autocomplete locations to drop-down menu locations as per the wiki link above. The plugin works with autocomplete but not with drop-down menus, so the issue should probably be "Location Required has no effect with drop-down menus".

**Comment by trains58554** [comment]
This is strange I just tested this with the dropdown menus and the location required plugin was working just fine for me. Is your site online? If you do not want to post your website address here you can pm me on the forms I am user trains58554.

Jay

**Comment by rnkn** [comment]
Hi Jay,

Thanks for giving this your attention, it's much appreciated.

http://alpha.filmingtonpost.com/

I've switched to the Modern theme with drop-down menus set as per the wiki. The location required plugin is enabled and is the only installed plugin. Still seems to have no effect.

One more thing that could be causing problems: the location data is all added by me (as the original Australian location data was in Spanish :P).

Any thoughts? If nothing jumps out I'll do a fresh install because I had another issue (https://github.com/osclass/OSClass/issues/84) that was unique to my installation.

**Comment by conejoninja** [comment]
Closing this due to being old. If the issue still persists, please reopen.
