### ISSUE TITLE
[Bug] Paypal plugin

### ISSUE THREAD

**Issue by trains58554** [osclass/osclass-plugins#69]
Hi 

@TurbineJesse and I found a bug in the paypal plugin. To reproduce this bug first you need to have pay per post enabled in the paypal plugin then create a new ad but do not pay for the ad just click over to your account and then go to the "item payment status" page and you will notice that the new add that you added and did not pay for did not show up in the list as not paid. 

To fix this edit the user_menu.php file line 6 and change it to read like so

``` php
    $items        = Item::newInstance()->findByUserID($_SESSION['userId'], $page * $itemsPerPage, $itemsPerPage);
```

Jay

**Comment by conejoninja** [comment]
Closing this due to being old. If the issue still persists, please reopen.

"Payments" plugin is the replacement for paypal plugin, and should be used instead
