### ISSUE TITLE
osc-mobile-theme cannot upload pics

### ISSUE THREAD

**Issue by trendless** [osclass/osclass-plugins#70]
Have tried Android ICS/GB, iOS 3/5; tried fullsize images and smaller. Does not upload properly, just kicks back to item entry, sans picture. If you tap to submit again without picture, it works fine.

**Comment by garciademarina** [comment]
I can upload images through android mobile, http://demo.osclass.org/horizontal/for-sale/animals/title-ad-mobile_68

Android version 2.2.2

With iOs devices is not posible upload images because browser cannot access to filesystem.
