### ISSUE TITLE
Facebook Connect logout

### ISSUE THREAD

**Issue by aftab1003** [osclass/osclass-plugins#72]
hello.
i am facing the log out problem while i am using Facebook Connect plugin.
log-in and create account works great. but when i try to log out , then there is no result.
it log me out from Facebook but not from OsClass.

**Comment by Diablos86** [comment]
an evergreen problem

**Comment by web2graphics** [comment]
yup, unfortunately!

**Comment by conejoninja** [comment]
https://github.com/osclass/osclass-plugins/issues/91 This is the same issue but with a little more information. I will close this.

**Comment by web2graphics** [comment]
Thank you for your effort and time, but the issue seems not to be completely addressed yet, after all.
