### ISSUE TITLE
Internal Server Error in show_printpdf();

### ISSUE THREAD

**Issue by gcalderon** [osclass/osclass-plugins#75]
Installed printpdf plugin OK
Added show_printpdf(); call in modern theme file "item.php"  at line 117 as follows:

116             </div>
117             <?php show_printpdf(); ?>
118             <div id="useful_info">

FIRST: I do not get a button image. I get an underlined link that says Download PDF.
SECOND: When I click on it I get: 

---

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@lograndoexito.tv and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.
## Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Since I'm not a programmer, I don't know how to fix it.  Any suggestions???

Gracias - German Calderon

**Comment by juanramon** [comment]
Please, the issues related to the plugins should be in the osclass plugins issue tracker: https://github.com/osclass/osclass-plugins/issues

**Comment by juanramon** [comment]
My mistake... I thought I was in the core section... Sorry.

**Comment by conejoninja** [comment]
I couldn't reproduce this issue, please give us more information
