### ISSUE TITLE
job plugin - problems with styles at oc-admin

### ISSUE THREAD

**Issue by garciademarina** [osclass/osclass-plugins#76]
add / edit item at oc-admin, lose the style, and slider cannot be used.

**Comment by conejoninja** [comment]
Maybe this issue should be closed?

Check these images: http://i.imgur.com/Cj0Dj.png   &   http://i.imgur.com/HuSLd.png

I didn't touch anything about it

**Comment by garciademarina** [comment]
yes, thanks
