### ISSUE TITLE
Sitemap Generator Install Bug

### ISSUE THREAD

**Issue by ghost** [osclass/osclass-plugins#84]
plugins_sitemap-generator_1.2
osclass version 2.4.1

When clicking install, the plugin installed success message is generated and redirects to sitemap generator help (sitemap.php). But the plugin is not being added to the database preferences table as installed or active. The plugin, after refreshing the page shows as not installed via manage plugins. As a result, cannot access the sitemap options via the admin panel to run a manual cron.

**Comment by conejoninja** [comment]
I could not reproduce the issue
