### ISSUE TITLE
unable to add region, city 

### ISSUE THREAD

**Issue by legionwon** [osclass/osclass-plugins#86]
i am not seeing any option to add city or region i have selected india onyl coutry add option is available

**Comment by feralou** [comment]
Hi @legionwon please let me know what plugin you are talking about so I know how to help you.

**Comment by juanramon** [comment]
I think that this issue is related to the core. If I'm wrong, feel free of re-open the issue.

**Comment by legionwon** [comment]
how can i add screentshot here so that it ill easy for you to know or can email you

**Comment by legionwon** [comment]
On Tue, Jul 31, 2012 at 11:49 AM, Juan Ramón Díaz <
reply@reply.github.com

> wrote:
> 
> I think that this issue is related to the core. If I'm wrong, feel free of
> re-open the issue.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/osclass/osclass-plugins/issues/86#issuecomment-7407875

   hi dear see i am sent you a screentshot in regions and city there is no
option i want to add but its not working

**Comment by legionwon** [comment]
I have been using Google Talk and thought you might like to try it
out. We can use it to call each other for free over the Internet. Here
is an invitation to download Google Talk. Give it a try!

---

You've been invited by Tausif khan to use Google Talk.

If you already have a Google account, log in to Gmail and accept this
chat invitation:
http://mail.google.com/mail/b-95ac80a656-82fd33020f-NI-dv6LSgXLxkLCxnMoMVCqdyNw

To sign up for a Google account and get started with Google Talk, you can visit:
http://mail.google.com/mail/a-95ac80a656-82fd33020f-NI-dv6LSgXLxkLCxnMoMVCqdyNw?pc=en_gb-rf---a

Learn more at:
http://www.google.com/intl/en/landing/accounts/

Thanks,
The Google Team
