### ISSUE TITLE
facebook connect plogin doesn't log out!

### ISSUE THREAD

**Issue by web2graphics** [osclass/osclass-plugins#91]
( this is the second time we are reporting this bug(also here: https://github.com/osclass/osclass-plugins/issues/72)
To reproduce the bug 
1- install OSClass v3.0
2- install the Facebook connect plug in
3- enter the AP-id and secret key of the facebook application vi osclass pluin manager
3.5- modify the yourwebsite/oc-content/themes/modern/header by placing the  code <?php fbc_button(); ?> after the code <a href="<?php echo osc_register_account_url() ; ?>"><?php _e('Register for a free account', 'modern'); ?></a>
4-using your current Facebook account try to connect to your osclass installed website
5- go ahead and authorize the application
6- now we are logged in successfully , but:
7- but logging out doesnt work at all!
the only way to log out from the website is to clear out cookies!!

**Comment by schopenhauer** [comment]
I have experienced the same problem. Not sure, if there's a workaround/solution available yet.

**Comment by web2graphics** [comment]
No there is none, I looked at multiple there websites to which osclass was installed and none have a fixed facebook connect!

**Comment by conejoninja** [comment]
The plugin has been updated to version 1.1, also the facebook php sdk has been updated, the plugin has been improved a little the login/logout process.
