### ISSUE TITLE
Carousel plug in/Admin menu

### ISSUE THREAD

**Issue by trinifirst** [osclass/osclass-plugins#93]
The link https://github.com/osclass/osclass-plugins/issues does not include the Carousel plug in. 
I installed it and it has messed up the Admin menu. The last 30% of the menu is no longer visible. I know it's the carousel, because when I uninstall it, the menu works again, but I really like havin it on my site.

Greg
NEW USER
www.trinifirst.com

**Comment by juanramon** [comment]
You should talk with the plugin developer, not us. Here it's not the right place, ask him in the forum.
