### ISSUE TITLE
Sitemap Generator makes faulty sitemap.xml with Swedish chars

### ISSUE THREAD

**Issue by Stiffe** [osclass/osclass-plugins#95]
I have problems with the sitemap.xml generated by the sitemap generator plugin.

When executing the sitemap.xml it halts at line 84, at the first Swedish char (in regions)

Seems like it cannot process Swedish letters, like åäö, which here seems to be rewritten (in html) to: 

å = &aring - with a trailing ;
Å = &Aring - with a trailing ;

ä = &auml - with a trailing ;
Ä = &Auml - with a trailing ;

ö = &ouml - with a trailing ;
Ö = &Ouml - with a trailing ;

In my case, the sitemap halts and gives an error at the first "problem".
Which occurs when it reaches the first region with a "Ö" in its name. In sitemap.xml
rewritten to "&Ouml"

The error looks like this:

---

"This page contains the following errors:
error on line 84 at column 78: Entity 'Ouml' not defined Below is a rendering of the page up to the first error."

---

This is somehow urgent because google webmasters gives the same error when processing my sitemap.xml.

Is there something I can change in the php-files?
If yes, what and where?

**Comment by qweno** [comment]
Hello,

I will appreciate some help to fix plugin sitemap installed on spanish sites (spanish char set), in the meanwhile our sitemaps are invalid...

Thanks
Regards

OSClass v.3.1.1 with the last sitemap plugin

The Document is not valid!

File Name: http://misitio.com/sitemap.xml
Fatal Error 26: Entity 'iacute' not defined in http://misitio.com/sitemap.xml on line 44 column 91
Fatal Error 26: Entity 'aacute' not defined in http://misitio.com/sitemap.xml on line 49 column 90
Fatal Error 26: Entity 'aacute' not defined in http://misitio.com/sitemap.xml on line 54 column 90
Fatal Error 26: Entity 'oacute' not defined in http://misitio.com/sitemap.xml on line 274 column 92
Fatal Error 26: Entity 'oacute' not defined in http://misitio.com/sitemap.xml on line 279 column 92
Fatal Error 26: Entity 'oacute' not defined in http://misitio.com/sitemap.xml on line 364 column 92
Fatal Error 26: Entity 'oacute' not defined in http://misitio.com/sitemap.xml on line 369 column 92
Fatal Error 26: Entity 'iacute' not defined in http://misitio.com/sitemap.xml on line 734 column 81
Fatal Error 26: Entity 'oacute' not defined in http://misitio.com/sitemap.xml on line 764 column 82
Fatal Error 26: Entity 'aacute' not defined in http://misitio.com/sitemap.xml on line 769 column 80
Fatal Error 26: Entity 'eacute' not defined in http://misitio.com/sitemap.xml on line 784 column 79
Fatal Error 26: Entity 'eacute' not defined in http://misitio.com/sitemap.xml on line 784 column 98
Fatal Error 26: Entity 'iacute' not defined in http://misitio.com/sitemap.xml on line 814 column 96
