### ISSUE TITLE
Download do not show in ad

### ISSUE THREAD

**Issue by okfree** [osclass/osclass-plugins#96]
Hi, we have installed and configured categories for digital goods plugins. It seams to work, no error message after uploading files, but when you go to check the ads no download function do appear. Nor the files show up in setting > stats. Any idea? We tried form admin user side, from web admin side, with small an big sized zip files.
Thank you

**Comment by conejoninja** [comment]
Hi,

Could you provide more information?
Which verison of osclass are you using?

Thanks

**Comment by conejoninja** [comment]
I couldn't reproduce the issue, it works fine for me, Anyway, I fix a very small error, download it from here : http://market.osclass.org/plugins/digital-goods_16
