### ISSUE TITLE
Horse Attributes BUG

### ISSUE THREAD

**Issue by styly** [osclass/osclass-plugins#99]
Hi there this plugin is great FIRST thing that i want to say so thank you.

But i have a bug as you can see if the photo no SKILLS appear ?

Cheers.

https://docs.google.com/open?id=0B82yHRsjcy2tSlZ1aWNrQmtWbDA

**Comment by juanramon** [comment]
We haven't done this plugin... Perhaps you should contact the one that made this plugin through the forum (I guess that it would be there where you downloaded the plugin). Sorry :disappointed:
